// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package repository

import (
	"database/sql"
)

type MozHost struct {
	ID                 int64
	Host               sql.NullString
	Type               sql.NullString
	Permission         sql.NullInt64
	Expiretype         sql.NullInt64
	Expiretime         sql.NullInt64
	Modificationtime   sql.NullInt64
	Isinbrowserelement sql.NullInt64
}

type MozPerm struct {
	ID               int64
	Origin           sql.NullString
	Type             sql.NullString
	Permission       sql.NullInt64
	Expiretype       sql.NullInt64
	Expiretime       sql.NullInt64
	Modificationtime sql.NullInt64
}
